server:
  port: 10001

spring:
  application:
    name: ka-job
# 链路追踪
#  sleuth:
#    enabled: false
#    sampler:
#      # 采样率 (1.0 表示 100% 追踪请求)
#      probability: 1.0


logging:
  level:
    root: warn
    com.cl.ka: debug

# feign 配置
feign:
  client:
    config:
      default:
        # 日志级别
        logger-level: full
        # 注解契约配置
        contract: feign.Contract.Default
