server:
  port: 10000

spring:
  application:
    name: ka-order
# 链路追踪
#  sleuth:
#    enabled: true
#    sampler:
#      # 采样率 (1.0 表示 100% 追踪请求)
#      probability: 1.0
  # kafka
  kafka:
    bootstrap-servers: kafka01.docker.com:9092,kafka02.docker.com:9093,kafka03.docker.com:9094
    producer:
      acks: 1
      retries: 1
    consumer:
      auto-offset-reset: latest
      max-poll-records: 1
      enable-auto-commit: true
      auto-commit-interval: 1000
    listener:
      concurrency: 3
    admin:
      properties:
        metadata.max.age.ms: 100000

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost.huawei.com:3306/ka_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ENC(v1:xSUqBYHO1lWmC3OKfo5ixfFxmjmSuVwbZ6/2gIg7ams=)
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # redis
  redis:
    host: redis.docker.com
    database: 0
    jedis:
      pool:
        max-active: 2000
        max-idle: 20
    port: 6379

httpclient:
  read-timeout: 10

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "info"
  endpoint:
    info:
      enabled: true

# mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.cl.ka.order.provide.model
  configuration:
    map-underscore-to-camel-case: true
      

logging:
  level:
    root: warn
    com.cl.ka: debug
#    org.apache.kafka.clients.producer: trace
#    org.apache.kafka.clients.producer.internals.Sender: trace
#    ## org.springframework.kafka.listener.KafkaMessageListenerContainer: trace
#    ## 重平衡
#    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: info

